/* tslint:disable */
/* eslint-disable */
/**
 * Assignment2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  UserInfoGet200Response,
  UserLoginPost200Response,
  UserLoginPostRequest,
} from '../models/index';
import {
    UserInfoGet200ResponseFromJSON,
    UserInfoGet200ResponseToJSON,
    UserLoginPost200ResponseFromJSON,
    UserLoginPost200ResponseToJSON,
    UserLoginPostRequestFromJSON,
    UserLoginPostRequestToJSON,
} from '../models/index';

export interface UserInfoGetRequest {
    authorization?: string;
}

export interface UserLoginPostOperationRequest {
    userLoginPostRequest?: UserLoginPostRequest;
}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * 
     * Get nickname
     */
    async userInfoGetRaw(requestParameters: UserInfoGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserInfoGet200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['Authorization'] = String(requestParameters['authorization']);
        }


        let urlPath = `/user/info`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserInfoGet200ResponseFromJSON(jsonValue));
    }

    /**
     * 
     * Get nickname
     */
    async userInfoGet(requestParameters: UserInfoGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserInfoGet200Response> {
        const response = await this.userInfoGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 
     * User login
     */
    async userLoginPostRaw(requestParameters: UserLoginPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserLoginPost200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/user/login`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UserLoginPostRequestToJSON(requestParameters['userLoginPostRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserLoginPost200ResponseFromJSON(jsonValue));
    }

    /**
     * 
     * User login
     */
    async userLoginPost(requestParameters: UserLoginPostOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserLoginPost200Response> {
        const response = await this.userLoginPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
