/* tslint:disable */
/* eslint-disable */
/**
 * Assignment2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Nick
 */
export interface Nick {
    /**
     * 
     * @type {string}
     * @memberof Nick
     */
    nickName: string;
}

/**
 * Check if a given object implements the Nick interface.
 */
export function instanceOfNick(value: object): value is Nick {
    if (!('nickName' in value) || value['nickName'] === undefined) return false;
    return true;
}

export function NickFromJSON(json: any): Nick {
    return NickFromJSONTyped(json, false);
}

export function NickFromJSONTyped(json: any, ignoreDiscriminator: boolean): Nick {
    if (json == null) {
        return json;
    }
    return {
        
        'nickName': json['nick_name'],
    };
}

export function NickToJSON(json: any): Nick {
    return NickToJSONTyped(json, false);
}

export function NickToJSONTyped(value?: Nick | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'nick_name': value['nickName'],
    };
}

