/* tslint:disable */
/* eslint-disable */
/**
 * Assignment2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TokenResp
 */
export interface TokenResp {
    /**
     * 
     * @type {string}
     * @memberof TokenResp
     */
    token: string;
}

/**
 * Check if a given object implements the TokenResp interface.
 */
export function instanceOfTokenResp(value: object): value is TokenResp {
    if (!('token' in value) || value['token'] === undefined) return false;
    return true;
}

export function TokenRespFromJSON(json: any): TokenResp {
    return TokenRespFromJSONTyped(json, false);
}

export function TokenRespFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokenResp {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'],
    };
}

export function TokenRespToJSON(json: any): TokenResp {
    return TokenRespToJSONTyped(json, false);
}

export function TokenRespToJSONTyped(value?: TokenResp | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token': value['token'],
    };
}

