/* tslint:disable */
/* eslint-disable */
/**
 * Assignment2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserLoginPostRequest
 */
export interface UserLoginPostRequest {
    /**
     * 
     * @type {string}
     * @memberof UserLoginPostRequest
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof UserLoginPostRequest
     */
    password: string;
}

/**
 * Check if a given object implements the UserLoginPostRequest interface.
 */
export function instanceOfUserLoginPostRequest(value: object): value is UserLoginPostRequest {
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function UserLoginPostRequestFromJSON(json: any): UserLoginPostRequest {
    return UserLoginPostRequestFromJSONTyped(json, false);
}

export function UserLoginPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserLoginPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'username': json['username'],
        'password': json['password'],
    };
}

export function UserLoginPostRequestToJSON(json: any): UserLoginPostRequest {
    return UserLoginPostRequestToJSONTyped(json, false);
}

export function UserLoginPostRequestToJSONTyped(value?: UserLoginPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'username': value['username'],
        'password': value['password'],
    };
}

