/* tslint:disable */
/* eslint-disable */
/**
 * Assignment2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserInfoGet200Response
 */
export interface UserInfoGet200Response {
    /**
     * 
     * @type {string}
     * @memberof UserInfoGet200Response
     */
    nickName: string;
}

/**
 * Check if a given object implements the UserInfoGet200Response interface.
 */
export function instanceOfUserInfoGet200Response(value: object): value is UserInfoGet200Response {
    if (!('nickName' in value) || value['nickName'] === undefined) return false;
    return true;
}

export function UserInfoGet200ResponseFromJSON(json: any): UserInfoGet200Response {
    return UserInfoGet200ResponseFromJSONTyped(json, false);
}

export function UserInfoGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserInfoGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'nickName': json['nick_name'],
    };
}

export function UserInfoGet200ResponseToJSON(json: any): UserInfoGet200Response {
    return UserInfoGet200ResponseToJSONTyped(json, false);
}

export function UserInfoGet200ResponseToJSONTyped(value?: UserInfoGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'nick_name': value['nickName'],
    };
}

