/* tslint:disable */
/* eslint-disable */
/**
 * Assignment2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserLoginPost200Response
 */
export interface UserLoginPost200Response {
    /**
     * 
     * @type {string}
     * @memberof UserLoginPost200Response
     */
    token: string;
}

/**
 * Check if a given object implements the UserLoginPost200Response interface.
 */
export function instanceOfUserLoginPost200Response(value: object): value is UserLoginPost200Response {
    if (!('token' in value) || value['token'] === undefined) return false;
    return true;
}

export function UserLoginPost200ResponseFromJSON(json: any): UserLoginPost200Response {
    return UserLoginPost200ResponseFromJSONTyped(json, false);
}

export function UserLoginPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserLoginPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'],
    };
}

export function UserLoginPost200ResponseToJSON(json: any): UserLoginPost200Response {
    return UserLoginPost200ResponseToJSONTyped(json, false);
}

export function UserLoginPost200ResponseToJSONTyped(value?: UserLoginPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token': value['token'],
    };
}

